Python 3.5 POCL:
  script:
  - export PY_EXE=python3.5
  - export PYOPENCL_TEST=portable
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.5
  - pocl
  - large-node
  except:
  - tags

Python 3.6 POCL:
  script:
  - export PY_EXE=python3.6
  - export PYOPENCL_TEST=portable
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.6
  - pocl
  - large-node
  except:
  - tags

Python 3.5 Conda:
  script:
  - export SUMPY_FORCE_SYMBOLIC_BACKEND=symengine
  - CONDA_ENVIRONMENT=.test-conda-env-py3.yml
  - REQUIREMENTS_TXT=.test-conda-env-py3-requirements.txt
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project-within-miniconda.sh
  - ". ./build-and-test-py-project-within-miniconda.sh"
  tags:
  - linux
  - large-node
  except:
  - tags

Python 2.7 POCL:
  script:
  - export PY_EXE=python2.7
  - export PYOPENCL_TEST=portable
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - pocl
  - large-node
  except:
  - tags

Documentation:
  script:
  - EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-docs.sh
  - ". ./build-docs.sh"
  tags:
  - python3.5
  only:
  - master

Flake8:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
  - ". ./prepare-and-run-flake8.sh pytential test"
  tags:
  - python3.5
  except:
  - tags
