name: test-conda-env-py3-macos
channels:
- conda-forge
- defaults
dependencies:
- git
- conda-forge::numpy
- conda-forge::sympy
- pocl=1.0
- islpy
- pyopencl
- python=3.5
- symengine=0.3.0
- python-symengine=0.3.0
- pyfmmlib
- osx-pocl-opencl
# things not in here: loopy boxtree pymbolic meshmode sumpy
